spring:
  datasource:
    url: jdbc:h2:file:./db
    username: sa
    password: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


hateoas:
  url:
    base: http://localhost:9088/api/posts


logging:
  level:
    org.zalando.logbook: trace

logbook:
  exclude:
    - /api/posts/comment