spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/migration?currentSchema=sb_flyway'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true
    user: postgres
    password: postgres
    baseline-version: 0
