spring:
  datasource:
    url: jdbc:h2:mem:eop
    username: user
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    redis:
      time-to-live: 10m