spring:
  datasource:
    url: 'jdbc:h2:mem:liquibase'
    username: user
    password: password
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml


